#!/usr/bin/env bash

source $(dirname $0)/environment

echo "Starting serve process..."
# TODO: Add case statement to allow stopping, starting, and restarting
# TODO: Add logic to detect both podman and docker, if both are installed, use podman as default "first found"

podman run -d --rm --name ${SERVE_NAME} -p ${SERVE_PORT}:8080 \
  -v "${SITE_DIR}:/var/www/html/:z" ${SERVE_IMAGE}

echo "Serving lab content on http://localhost:${SERVE_PORT}/index.html"
