#!/usr/bin/env bash

source $(dirname $0)/environment

echo "Starting build process..."
echo "Removing old site..."
rm -rf ${SITE_DIR}/*
echo "Building new site..."

podman run --rm --name ${ANTORA_NAME} --platform linux/amd64 \
  -v "./:/antora:z" ${ANTORA_IMAGE} --stacktrace ${ANTORA_PLAYBOOK}

echo "Build process complete. Check the ${SITE_DIR} folder for the generated site."
echo "To view the site locally, run the following command: ./utilities/lab-serve"
echo "If already running then browse to http://localhost:${SERVE_PORT}/index.html"
